version: '3.1'

services:
  aws-ecs-demo:
    build: 
      context: ./
      dockerfile: ./Dockerfile 
      args:
        - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
        - PINECONE_API_KEY=${PINECONE_API_KEY}
        - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
        - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
        - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
    container_name: medical-chatbot
    ports:
      - 5000:8080
    environment:
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
    network_mode: bridge